name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configure Gradle caching
        uses: gradle/actions/setup-gradle@v3

      - name: Build & run unit tests with coverage
        run: ./gradlew clean testDebugUnitTest jacocoTestReport assembleDebug --stacktrace

      - name: Upload unit test report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Upload coverage report (JaCoCo HTML)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: app/build/reports/jacoco/jacocoTestReport/html/

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
